### ISSUE TITLE
What is password for abc? 

### ISSUE THREAD

**Issue by abohnenberger** [bluxmit/alnoda-workspaces#14]
I need to sudo -i to write files

02:57:20 with abc in ~p took 8m 35s ✦ ➜ sudo vi /etc/ansible/hosts
[sudo] password for abc: 
Sorry, try again.
[sudo] password for abc: 
Sorry, try again.
[sudo] password for abc:

**Comment by amlucent** [comment]
the root or abc password is not shared but you can change it anytime.  From your container host run

`docker exec -it --user=root <ContainerName> /bin/zsh`

then youll be root and you can execute a `passwd` or `passwd abc` or even just edit the sudorers file to your liking.

**Comment by abohnenberger** [comment]
Thank You that worked.

**Comment by bluxmit** [comment]
Thanks @abohnenberger
