### ISSUE TITLE
the WRK_HOST variable needs to be inserted in ara config at creation

### ISSUE THREAD

**Issue by amlucent** [bluxmit/alnoda-workspaces#15]
I found this issue while troubleshooting my Error 400 for Ansible Ara.  https://ara.readthedocs.io/en/latest/troubleshooting.html

The container's WRK_HOST variable needs to be inserted in ara `~/.ara/server/settings.yaml` at container creation to prevent an error 400 if using a url that is not loopback or localhost.

**Comment by bluxmit** [comment]
This issue should be fixed in the latest updates
