### ISSUE TITLE
MkDocs-MagicSpace Enhancement: Easier way to Include docs from other repositories

### ISSUE THREAD

**Issue by jdoiro3** [bluxmit/alnoda-workspaces#16]
This is a suggestion. Let me know if I should move it somewhere else since this isn't an issue with the project.

In the documentation for MkDocs Magicspace it mentions using symbolic links to include docs from other repos. Another way to do this now is via the [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin). I suggest you check it out and see if it makes sense to include this plugin within the project.

**Comment by bluxmit** [comment]
Added in the release 2.0
