### ISSUE TITLE
ttyd, mc, and htop fail to start in ide-workspace and terraform-ansible

### ISSUE THREAD

**Issue by scarolac** [bluxmit/alnoda-workspaces#17]
Midnight Commander, htop, and the terminal are not launching with the app. Checking docker logs shows:
```
2022-05-15 01:38:35,592 INFO exited: htop (exit status 2; not expected)
2022-05-15 01:38:35,592 INFO exited: mc (exit status 2; not expected)
2022-05-15 01:38:35,593 INFO exited: ttyd (exit status 2; not expected)
```
shortly after they started.

I have only tried those two workspaces for now and I know terraform is built on top of the ide one.
Connecting to the container lets me run mc and htop, but ttyd gives me a `bash: /usr/bin/ttyd: cannot execute binary file: Exec format error` and looking at the dockerfile it looks like you used the arm64 version for ttyd. (line 126 in ubuntu18, and 129 in ubuntu20 dockerfiles)

I downloaded ttyd.x86_64 and dumped it in the container replacing the existing one, and now it works. So you might want to update the dockerfile if it was meant to be the x86_64 version.

**Comment by bluxmit** [comment]
Thank you for reporting, it's being fixed now in all affected images

**Comment by scarolac** [comment]
Also noticed you pull the python2 version of docker-systemctl-replacement and then install python3, and it throws an error on container boot. I wasn't sure what was using systemctl though when I was playing with it.

**Comment by bluxmit** [comment]
All mentioned issues were fixed
