### ISSUE TITLE
sudo creds requested

### ISSUE THREAD

**Issue by rrw357** [bluxmit/alnoda-workspaces#18]
Is it possible to be provided with the credentials for the abc account that is being referenced. I would like to be able to create additional users. Checked the documentation and didnt see and instructions for the sudo password for the abc user.

also receiving this error when attempting to create a remote instance:

19:32:44 with abc in ~/utils took 27s ➜ python remote.py --workspace="base-workspace" --port="8020" --host="89.89.89.89" --user="Test" --password="test123"
Traceback (most recent call last):
  File "remote.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by bluxmit** [comment]
Hi, there is no sudo password for the abc user. This user is allowed for several passwordless sudo actions such as apt-get. But you can simply run workspace as root user, i.e. docker run --user=root ... 
Thanks for reporting the remote issue
