### ISSUE TITLE
copying my local ssh into a running instance

### ISSUE THREAD

**Issue by engnr-a** [bluxmit/alnoda-workspaces#20]
I am very new to docker. Can someone help explain how I can copy local ssh key into a running instance of this. I intend to simulate several instance of VM to practice ansible

**Comment by engnr-a** [comment]
Is it possible to do something like `ssh-copy-id -i ~/.ssh/id_rsa.pub 172.17.0.2`....I get resource temporarily unavailable

**Comment by bluxmit** [comment]
If you are using ansible-terraform workspace, then it has browser-based filebrowser, exactly for this problems. Open quickstart page on localhost:8020, open filebrowser and "upload" your ssh key to any folder
