### ISSUE TITLE
Workspace UI doesn't work due to mkdocs failing

### ISSUE THREAD

**Issue by devitt94** [bluxmit/alnoda-workspaces#4]
**Note: I am running on a Mac with M1 chip.**

Running the below:

`docker run --name space-1 -d -p 8020-8035:8020-8035 alnoda/python-workspace`

and navigating to http://localhost:8020/ I see the following.

![image](https://user-images.githubusercontent.com/5331126/149305125-2d714d24-6aad-44e0-a94f-9ce948d5897d.png)

I see the following in the container logs

```
2022-01-13 09:35:09,118 INFO success: mkdocs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-13 09:35:11,024 INFO exited: mkdocs (exit status 1; not expected)
2022-01-13 09:35:11,403 INFO spawned: 'mkdocs' with pid 269
2022-01-13 09:35:12,712 INFO success: mkdocs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-01-13 09:35:16,225 INFO exited: mkdocs (exit status 1; not expected)
```

**Comment by bluxmit** [comment]
Hi @devitt94, 
thank you for reporting! 

May I ask you to exec into the docker image of the workspace and (or using the terminal http://localhost:8026/) and `cat /var/log/mkdocs/mkdocs-stderr.log` and `cat /var/log/mkdocs/mkdocs-stdout.log`?

May I also ask you to check if docker has enough space left on your machine? You could try to remove some stopped docker containers and docker images that you don't use anymore, and try again.

Is IDE running on http://localhost:8025? If not, Could you please exec into the docker image of the workspace and (or using the terminal http://localhost:8026/) and `cat /var/log/theia/theia-stderr.log`?

**Comment by devitt94** [comment]
@bluxmit thanks for the fast response!

See mkdocs logs below.

```
10:56:24 with abc in ~p took 5s ➜ cat /var/log/mkdocs/mkdocs-stdout.log
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
[Errno 38] Function not implemented
```

```
10:56:26 with abc in ~p ➜ cat /var/log/mkdocs/mkdocs-stderr.log
INFO     -  Building documentation...
WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO     -  [macros] - Macros arguments: {'module_name': 'macros/helpers', 'modules': [], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'verbose': False}
INFO     -  [macros] - Found local Python module 'macros/helpers' in: /home/docs
INFO     -  [macros] - Found external Python module 'macros/helpers' in: /home/docs
INFO     -  [macros] - Extra variables (config file): ['homepage', 'host_url']
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Cleaning site directory
WARNING  -  Documentation file 'docs.md' contains a link to 'img/workspace-demo.gif' which is not found in the documentation files.
INFO     -  Documentation built in 2.30 seconds
INFO     -  Building documentation...
WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO     -  [macros] - Macros arguments: {'module_name': 'macros/helpers', 'modules': [], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'verbose': False}
INFO     -  [macros] - Found local Python module 'macros/helpers' in: /home/docs
INFO     -  [macros] - Found external Python module 'macros/helpers' in: /home/docs
INFO     -  [macros] - Extra variables (config file): ['homepage', 'host_url']
INFO     -  [macros] - Extra filters (module): ['pretty']
INFO     -  Cleaning site directory
WARNING  -  Documentation file 'docs.md' contains a link to 'img/workspace-demo.gif' which is not found in the documentation files.
INFO     -  Documentation built in 1.34 seconds
INFO     -  Building documentation...
WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
```

All the other ports (including Theia IDE on 8025) seem to be working fine.

I have pruned all other docker containers/images on my machine so I don't think space is the issue - how much memory should I expect it to use?

**Comment by bluxmit** [comment]
thank you for the logs
I am looking into it

RE memory, looks like it is not the memory issue. It would be only if there is nearly nothing left for docker. 
Best

**Comment by bluxmit** [comment]
@devitt94 , can I ask you to help me a little?

Could you please completely force delete the image, and try to pull & run it again? First `docker run --name space-2 -d -p 8020-8035:8020-8035 alnoda/workspace-in-docker:18.04-0.11` and then `docker run --name space-3 -d -p 8020-8035:8020-8035 alnoda/workspace-in-docker:latest`
I need this to rule out the possibility that you are using some old version
Thank you!

**Comment by bluxmit** [comment]
@devitt94 , I can't reproduce your issue. can I ask you to commit the workspace to a new image, and send me a file or push it to the public docker registry?

**Comment by MikeCantCode** [comment]
I had this same issue running Docker on an M1 Mac. I was able to get mkdocs to serve the site by upgrading it to `mkdocs-1.2.3`. 

@bluxmit , maybe update [mkdocs-requirements.txt](https://github.com/bluxmit/alnoda-workspaces/blob/main/workspaces/base-workspace/mkdocs-requirements.txt#L1) to the new version?

**Comment by bluxmit** [comment]
Done! hank you @MikeCantCode 
This fix was applied to all the workspaces, not only to the python-workspace.
PS: unfortunately, I can't test on M1 chip
